#!/bin/sh
# ========================================================================
# Copyright 1988-2006 University of Washington
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# ========================================================================

# Program:	Authenticator Linkage Generator
#
# Author:	Mark Crispin
#
# Date:		5 December 1995
# Last Edited:	30 August 2006

# Erase old authenticators list
rm -f auths.c
touch auths.c

# Now define the new list
for authenticator
 do
  if [ -f Makefile."$authenticator" ]; then
    make -f Makefile."$authenticator" `cat SPECIALS`
  fi
  echo "extern AUTHENTICATOR auth_"$authenticator";" >> linkage.h
  echo "  auth_link (&auth_"$authenticator");		/* link in the $authenticator authenticator */" | cat >> linkage.c
  echo "#include \"auth_"$authenticator".c\"" >> auths.c
done
