# ========================================================================
# Copyright 1988-2006 University of Washington
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# ========================================================================


# Program:	MTEST Makefile for Windows 9x and Windows NT
#
# Author:	Mark Crispin
#
# Date:		25 February 1996
# Last Edited:	30 August 2006


C = ..\c-client
CCLIENTLIB = $C\cclient.lib
LIBS = $(CCLIENTLIB) ws2_32.lib winmm.lib advapi32.lib
OSCOMPAT = /DWIN32 /D_WIN32_WINNT=0x0501
VSCOMPAT = /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE
CFLAGS= -I$C /MT /W3 $(OSCOMPAT) $(VSCOMPAT) -nologo $(EXTRACFLAGS)

mtest: $(CCLIENTLIB) mtest.obj
	LINK /NOLOGO mtest.obj $(LIBS)

mtest.obj: $C\mail.h $C\smtp.h $C\misc.h $C\osdep.h mtest.c

$(CCLIENTLIB):
	@echo Make c-client first
	false

clean:
	del *.obj *.exe *.lib *.exp || rem

# A monument to a hack of long ago and far away...
love:
	@echo not war?
